### PR TITLE
Converted actions to YAML syntax

### PR DESCRIPTION
**Pull request by manicki**
The result of running `migrate-actions` tool,
as per https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax.

### CODE REVIEW

**Comment by manicki** [comment]
https://github.com/wmde/vuex-helpers/pull/5/commits/c781cae498f514a255be69612a31df8771ac176d is a result of running the recommended migration script but it does look wrong at glance (dependencies between action seems to have got missed).
Also the build failure shows the automated migration didn't really work: https://github.com/wmde/vuex-helpers/runs/238623339

**Comment by wiese** [comment]
It does not look like [it](https://github.com/wmde/vuex-helpers/runs/238623339) went horribly wrong - just the tagging funnel seems to be overreacting. Don't have time to research but maybe - given this is still somewhat in beta - something really is not quite right about interpreting the exit code ("##[error]Docker run failed with exit code 78") in this case.

**Comment by manicki** [comment]
Yup, looks like this was about handling the exit code: https://github.com/actions/migrate/issues/42. I've followed the advice given there and dropped the filtering step, and included filtering in the Publishing step.
I've just copied code from somewhere, and am not at all sure whether it is the best approach. Among other things, I am not sure why/if "created" is a better event type to filter by than "published". https://help.github.com/en/articles/events-that-trigger-workflows#release-event-release is not very informative on this.

Also it looks the repo branch protection settings would need to be changed before merging this as there is no longer "Test" action.
Actually, I am not even convinced the single "Build" action with multiple steps like the tool has generated it is the best structure for defining those workflows.

**Review by wiese — APPROVED** [review]
Thanks for digging this up.

As you mentioned we are (very much so) witnessing a product under development - I'd be ok with accepting the spotty doc and go with the filter rules you dug up; especially as "release created" does not sound totally unintuitive.

That said, the [announcement](https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax) puzzles me, especially as `act` totally is not ready for it (https://github.com/nektos/act/issues/74 / https://github.com/nektos/act/issues/79) but with the "old" syntax being deprecated today, let's do this and find out if it actually works.

As a perk (compared to before) this filter does now seem to get applied before a container is spun up (try and expand the filter step in the build log) so you are also paying into our environmental sustainability goals.

Am sad to see workflow rendering go this way but [maybe it will make a return](https://github.community/t5/GitHub-Actions/Workflow-rendering-doesn-t-work-with-yaml-files/m-p/31613).

FTR: did not touch the branch protection

**Pull request merged**
